jobs: 
  include:
    - os: linux

language: golang
go: "1.13"
env:
  - LIBVIRT=2.5.0  EXT=xz
  - LIBVIRT=3.10.0  EXT=xz
  - LIBVIRT=4.10.0  EXT=xz
  - LIBVIRT=5.5.0  EXT=xz
install:
  - sudo apt-get -qqy build-dep libvirt
  - sudo apt-get -qqy install curl qemu-system-x86 sasl2-bin
  - sudo mkdir -p /usr/src && sudo chown $(id -u) /usr/src
  - curl -O -s https://libvirt.org/sources/libvirt-${LIBVIRT}.tar.${EXT}
  - tar -C /usr/src -xf libvirt-${LIBVIRT}.tar.${EXT}
  - pushd /usr/src/libvirt-${LIBVIRT}
  - |
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
                    --without-polkit \
                    --without-esx --without-vbox --without-xen --without-libxl \
                    --with-qemu --with-lxc
  - make
  - sudo make install
  - popd
  - sudo cp tests/libvirtd.sasl /etc/sasl2/libvirt.conf
  - sudo libvirtd -d -l -f tests/libvirtd.conf
  - sudo virtlogd -d || true
  - sudo chmod a+rwx /var/run/libvirt/libvirt-sock*
  - echo "pass" | sudo saslpasswd2 -p -a libvirt user

script: "
  sudo apt install qemu qemu-kvm libvirt-bin  bridge-utils  virt-manager
  sudo service libvirtd start
"
