jobs: 
  include:
    - os: linux

language: golang
go: "1.13"
env:
  - LIBVIRT=5.5.0  EXT=xz
install:
  - sudo apt-get -qqy build-dep libvirt
  - sudo apt-get -qqy install curl qemu-system-x86 sasl2-bin
  - sudo mkdir -p /usr/src && sudo chown $(id -u) /usr/src
  - curl -O -s https://libvirt.org/sources/libvirt-${LIBVIRT}.tar.${EXT}
  - tar -C /usr/src -xf libvirt-${LIBVIRT}.tar.${EXT}
  - pushd /usr/src/libvirt-${LIBVIRT}
  - |
        ./configure --prefix=/usr --localstatedir=/var --sysconfdir=/etc \
                    --without-polkit \
                    --without-esx --without-vbox --without-xen --without-libxl \
                    --with-qemu --with-lxc
  - make
  - sudo make install
  - popd
  - sudo cp tests/libvirtd.sasl /etc/sasl2/libvirt.conf
  - sudo libvirtd -d -l -f tests/libvirtd.conf
  - sudo virtlogd -d || true
  - sudo chmod a+rwx /var/run/libvirt/libvirt-sock*
  - echo "pass" | sudo saslpasswd2 -p -a libvirt user
  - sudo apt install qemu-kvm libvirt-daemon libvirt-daemon-system network-manager
  - export CRC_VERSION=latest
  - export SecretFile=pull-secrets.txt
  - export RAM_MEMORY=16384
  - export CPUS=4

  - set -e -x
  - curl -SLO  https://mirror.openshift.com/pub/openshift-v4/clients/crc/${CRC_VERSION}/crc-linux-amd64.tar.xz
  - tar -xvf crc-linux-amd64.tar.xz --strip-components=1
  - chmod +x ./crc
  - mv ./crc /usr/local/bin/crc

  - crc version
  - crc config set skip-check-root-user true
  - crc config set nameserver 8.8.8.8
  - crc setup
  - crc start --cpus=${CPUS} --memory=${RAM_MEMORY} --pull-secret-file=${SecretFile} --log-level debug


script: "
  ls
"
